// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
// bpf headers
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/usdt.bpf.h>
// internal headers
#include <datacrumbs/server/bpf/macros.bpf.h>
#include <datacrumbs/server/bpf/shared.h>

DATACRUMBS_MAP(pid_map, u32, u64, 1024);
DATACRUMBS_MAP(fn_pid_map, struct fn_key_t, struct fn_value_t);
DATACRUMBS_MAP(event_arg_config_map, u64, struct runtime_event_config_t,
               DATACRUMBS_MAX_RUNTIME_FUNCTIONS);
struct {
  __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
  __uint(max_entries, 1);
  __type(key, u32);
  __type(value, struct fn_value_t);
} scratch_fn_value_map SEC(".maps");

#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
DATACRUMBS_MAP(failed_request, u32, u32, 128);
DATACRUMBS_RINGBUF(output, 1024 * 1024U * DATACRUMBS_TRACE_RINGBUF_SIZE_MB);
#else
DATACRUMBS_MAP(profile, struct profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP(usdt_profile, struct usdt_profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP(latest_interval, int, unsigned long long, 128);
#endif
DATACRUMBS_MAP(file_map, char[MAX_STR_READ_LEN], u32, 1024);

#if defined(DATACRUMBS_ENABLE_HW_COUNTERS) && (DATACRUMBS_ENABLE_HW_COUNTERS == 1)
// Hardware PMU counter fds, one perf event per (cpu, slot) at index
// cpu*DATACRUMBS_HW_COUNTER_SLOTS + slot. max_entries (ncpu*SLOTS) is sized by
// userspace before load.
struct {
  __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY);
  __uint(key_size, sizeof(int));
  __uint(value_size, sizeof(int));
} hwc_pmu SEC(".maps");
// Control: index 0 holds the number of active counters (0..SLOTS), set by
// userspace after load. Lets the BPF read loop touch only configured counters.
struct {
  __uint(type, BPF_MAP_TYPE_ARRAY);
  __uint(max_entries, 1);
  __type(key, u32);
  __type(value, u32);
} hwc_ctl SEC(".maps");
#endif
