#ifndef __DATACRUMBS_SERVER_BPF_COMMON_H
#define __DATACRUMBS_SERVER_BPF_COMMON_H

// Generated by DataCrumbs during system build
#include <datacrumbs/server/bpf/vmlinux.h>
// bpf headers
#include <bpf/bpf_core_read.h>
#include <bpf/bpf_helpers.h>
#include <bpf/bpf_tracing.h>
#include <bpf/usdt.bpf.h>
// internal headers
#include <datacrumbs/server/bpf/macros.bpf.h>
#include <datacrumbs/server/bpf/shared.h>

DATACRUMBS_MAP_EXTERN(pid_map, u32, u64, 1024);
DATACRUMBS_MAP_EXTERN(fn_pid_map, struct fn_key_t, struct fn_value_t);
DATACRUMBS_MAP_EXTERN(probe_guard, u64, struct probe_guard_t, DATACRUMBS_MAX_RUNTIME_FUNCTIONS);
DATACRUMBS_MAP_EXTERN(event_arg_config_map, u64, struct runtime_event_config_t,
                      DATACRUMBS_MAX_RUNTIME_FUNCTIONS);
extern struct {
  __uint(type, BPF_MAP_TYPE_PERCPU_ARRAY);
  __uint(max_entries, 1);
  __type(key, u32);
  __type(value, struct fn_value_t);
} scratch_fn_value_map SEC(".maps");

#define DATACRUMBS_PMU_ARRAY_EXTERN(name)      \
  extern struct {                              \
    __uint(type, BPF_MAP_TYPE_PERF_EVENT_ARRAY); \
    __uint(key_size, sizeof(u32));             \
    __uint(value_size, sizeof(u32));           \
    __uint(max_entries, 256);                  \
  } name SEC(".maps");
DATACRUMBS_PMU_ARRAY_EXTERN(pmu_counter0)
DATACRUMBS_PMU_ARRAY_EXTERN(pmu_counter1)
DATACRUMBS_PMU_ARRAY_EXTERN(pmu_counter2)
extern struct {
  __uint(type, BPF_MAP_TYPE_ARRAY);
  __uint(max_entries, 1);
  __type(key, u32);
  __type(value, u32);
} pmu_ctl SEC(".maps");

#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
DATACRUMBS_MAP_EXTERN(failed_request, u32, u32, 128);
DATACRUMBS_RINGBUF_EXTERN(output, 1024 * 1024U * DATACRUMBS_TRACE_RINGBUF_SIZE_MB);
#else
DATACRUMBS_MAP_EXTERN(profile, struct profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP_EXTERN(usdt_profile, struct usdt_profile_key_t, struct profile_value_t, 1024);
DATACRUMBS_MAP_EXTERN(latest_interval, int, unsigned long long, 128);
#endif
DATACRUMBS_MAP_EXTERN(file_map, char[MAX_STR_READ_LEN], u32, 1024);

#if defined(DATACRUMBS_ENABLE_INCLUSION_PATH) && (DATACRUMBS_ENABLE_INCLUSION_PATH == 1)
DATACRUMBS_TRIE_EXTERN(inclusion_path_trie, struct string_t, struct string_t);
#endif

static inline __attribute__((always_inline)) u32 hash_str(const char* str, size_t len) {
  u32 hash = 5381;
  for (int i = 0; i < 128; ++i) {
    if (i >= len) break;
    hash = ((hash << 5) + hash) + str[i];
  }
  return hash;
}

static inline __attribute__((always_inline)) u32 hash_and_store(struct string_t* str, size_t len) {
  u32* existing = bpf_map_lookup_elem(&file_map, str);
  if (existing) {
    return *existing;  // Return existing hash
  }
  u32 hash = hash_str(str->str, len);
  // Store new hash
  bpf_map_update_elem(&file_map, str, &hash, BPF_ANY);
  return hash;
}

#if defined(DATACRUMBS_ENABLE_INCLUSION_PATH) && (DATACRUMBS_ENABLE_INCLUSION_PATH == 1)
// Returns 1 if any prefix in trie matches 'str' of length 'len', else 0
static inline __attribute__((always_inline)) int prefix_search(void* trie, struct string_t* key) {
  struct string_t* found = (struct string_t*)bpf_map_lookup_elem(trie, key);
  if (found) {
    int prefix_len = 0;
    int is_prefix = 1;
    for (int i = 0; i < MAX_STR_READ_LEN && i < found->len; ++i) {
      if (found->str[i] == '\0') break;
      if (found->str[i] != key->str[i]) {
        is_prefix = 0;
        break;
      }
      prefix_len++;
    }
    if (is_prefix && prefix_len * 8 == found->len) {
      // found->str is an exact prefix of key->str
      is_prefix = 1;
    } else {
      is_prefix = 0;
    }
    if (is_prefix) {
      DBG_PRINTK("Found prefix:%s value:%u", key->str, prefix_len);
      return 1;
    } else {
      DBG_PRINTK("Not Found prefix:%s value:%d found-len:%d", key->str, prefix_len, found->len);
      return 0;
    }
  }
  DBG_PRINTK("Not Found prefix:%s", key->str);
  return 0;
}
#else
static inline __attribute__((always_inline)) int prefix_search(void* trie, struct string_t* key) {
  return 1;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
static inline __attribute__((always_inline)) int mark_failed_events() {
  u32 key = DATACRUMBS_FAILED_EVENTS_KEY;
  u32* failed_value = bpf_map_lookup_elem(&failed_request, &key);
  if (failed_value == NULL) {
    u32 init_val = 0;
    bpf_map_update_elem(&failed_request, &key, &init_val, BPF_NOEXIST);
    failed_value =
        bpf_map_lookup_elem(&failed_request, &key);  // Lookup again to get the new value's address
  }
  if (failed_value != NULL) {
    (*failed_value)++;
    DBG_PRINTK("Captured failed event: %d %d\n", key, *failed_value);
    return *failed_value;
  }
  return 0;
}
#else
static inline __attribute__((always_inline)) int mark_failed_events() {
  return 0;
}
#endif
#endif

#if defined(DATACRUMBS_TRACE_ALL_PROCESSES) && (DATACRUMBS_TRACE_ALL_PROCESSES == 1)
static inline __attribute__((always_inline)) int need_tracing(struct fn_key_t* key, u64* start_ts) {
  key->id = bpf_get_current_pid_tgid();
  return 1;
}
#else
static inline __attribute__((always_inline)) int need_tracing(struct fn_key_t* key, u64* start_ts) {
  key->id = bpf_get_current_pid_tgid();  // full tgid|tid; fn_pid_map still pairs entry/exit per-thread
  u32 tgid = key->id >> 32;              // gate by process so worker threads trace too, not just the
                                         // thread that called datacrumbs_start
  start_ts = (u64*)bpf_map_lookup_elem(&pid_map, &tgid);
  if (start_ts == 0 || key->id == 0) return 0;
  return 1;
}
#endif

#ifndef DATACRUMBS_HOT_PROBE_WINDOW_NS
#define DATACRUMBS_HOT_PROBE_WINDOW_NS 100000000ULL  // 100ms window
#endif
#ifndef DATACRUMBS_HOT_PROBE_MAX_PER_WINDOW
#define DATACRUMBS_HOT_PROBE_MAX_PER_WINDOW 20000ULL  // ~200k events/s/probe cap
#endif

// Rate-limit a runaway (e.g. busy-poll) probe: returns 1 to drop this hit once a probe exceeds the
// per-window cap, so one hot symbol cannot flood the ring. Per-event_id sliding window.
static inline __attribute__((always_inline)) int hot_probe_drop(u64 event_id, u64 te) {
  struct probe_guard_t* g = (struct probe_guard_t*)bpf_map_lookup_elem(&probe_guard, &event_id);
  if (g == NULL) {
    struct probe_guard_t init = {.win_ts = te, .count = 1, .dropped = 0};
    bpf_map_update_elem(&probe_guard, &event_id, &init, BPF_ANY);
    return 0;
  }
  if (te - g->win_ts >= DATACRUMBS_HOT_PROBE_WINDOW_NS) {
    g->win_ts = te;
    g->count = 0;
  }
  g->count += 1;
  if (g->count > DATACRUMBS_HOT_PROBE_MAX_PER_WINDOW) {
    g->dropped += 1;
    return 1;
  }
  return 0;
}

static inline __attribute__((always_inline)) const struct runtime_event_config_t*
resolve_event_config(u64 attach_cookie) {
  return (const struct runtime_event_config_t*)bpf_map_lookup_elem(&event_arg_config_map,
                                                                   &attach_cookie);
}

static inline __attribute__((always_inline)) struct fn_value_t* get_scratch_fn_value(void) {
  u32 key = 0;
  return (struct fn_value_t*)bpf_map_lookup_elem(&scratch_fn_value_map, &key);
}

// Active PMU counter count (0 = off); one cheap array lookup, so the off path stays lookup-only.
static inline __attribute__((always_inline)) u32 pmu_active_count(void) {
  u32 k = 0;
  u32* n = (u32*)bpf_map_lookup_elem(&pmu_ctl, &k);
  return n ? *n : 0;
}

// Read the current cpu's value for each active counter into out[]. n is pmu_active_count().
static inline __attribute__((always_inline)) void pmu_read(u64* out, u32 n) {
  struct bpf_perf_event_value v = {};
  if (n > 0 && !bpf_perf_event_read_value(&pmu_counter0, BPF_F_CURRENT_CPU, &v, sizeof(v)))
    out[0] = v.counter;
  if (n > 1 && !bpf_perf_event_read_value(&pmu_counter1, BPF_F_CURRENT_CPU, &v, sizeof(v)))
    out[1] = v.counter;
  if (n > 2 && !bpf_perf_event_read_value(&pmu_counter2, BPF_F_CURRENT_CPU, &v, sizeof(v)))
    out[2] = v.counter;
}

// Snapshot counters at entry into the scratch fn_value (no-op when PMU is off).
static inline __attribute__((always_inline)) void pmu_snapshot_entry(struct fn_value_t* fn) {
  u32 n = pmu_active_count();
  fn->pmu_count = n;
  if (n) pmu_read(fn->pmu_start, n);
}

// At exit, write per-counter (exit-entry) deltas into the event (no-op when PMU is off).
static inline __attribute__((always_inline)) void pmu_delta_exit(const struct fn_value_t* fn,
                                                                 struct generic_event_t* event) {
  event->pmu_count = fn->pmu_count;
  if (!fn->pmu_count) return;
  u64 now[DATACRUMBS_MAX_PMU] = {};
  pmu_read(now, fn->pmu_count);
#pragma unroll
  for (int i = 0; i < DATACRUMBS_MAX_PMU; ++i) event->pmu[i] = now[i] - fn->pmu_start[i];
}

static inline __attribute__((always_inline)) int mark_current_pid_traced(void) {
  const u64 tsp = bpf_ktime_get_ns();
  const u64 current = bpf_get_current_pid_tgid();
  const u32 tgid = current >> 32;  // mark the process; the gate is per-tgid
  if (tgid == 0) return 0;
  bpf_map_update_elem(&pid_map, &tgid, &tsp, BPF_ANY);
  DBG_PRINTK("Marked tracing tgid=%u", tgid);
  return 0;
}

static inline __attribute__((always_inline)) int unmark_current_pid_traced(void) {
  const u64 current = bpf_get_current_pid_tgid();
  const u32 tgid = current >> 32;
  if (tgid == 0) return 0;
  bpf_map_delete_elem(&pid_map, &tgid);
  DBG_PRINTK("Unmarked tracing tgid=%u", tgid);
  return 0;
}

static inline __attribute__((always_inline)) void reset_captured_args(struct fn_value_t* fn) {
#pragma unroll
  for (int index = 0; index < DATACRUMBS_MAX_CAPTURE_ARGS; ++index) {
    fn->args[index] = 0;
    fn->arg_data_len[index] = 0;
    fn->arg_data_status[index] = 0;
    __builtin_memset(fn->arg_data[index], 0, sizeof(fn->arg_data[index]));
  }
  fn->arg_count = 0;
}

static inline __attribute__((always_inline)) void copy_captured_args_to_event(
    const struct fn_value_t* fn, struct generic_event_t* event) {
  event->arg_count = fn->arg_count;
#pragma unroll
  for (int index = 0; index < DATACRUMBS_MAX_CAPTURE_ARGS; ++index) {
    event->args[index] = fn->args[index];
    event->arg_data_len[index] = fn->arg_data_len[index];
    event->arg_data_status[index] = fn->arg_data_status[index];
    __builtin_memcpy(event->arg_data[index], fn->arg_data[index], DATACRUMBS_MAX_CAPTURE_BYTES);
  }
}

static inline __attribute__((always_inline)) void capture_runtime_args(
    struct pt_regs* ctx, const struct runtime_event_config_t* config, struct fn_value_t* fn) {
  unsigned int arg_index;
  unsigned int num_bytes;
  unsigned long long raw_value;
  long err;
  const unsigned long long raw_arg0 = PT_REGS_PARM1(ctx);
  const unsigned long long raw_arg1 = PT_REGS_PARM2(ctx);
  const unsigned long long raw_arg2 = PT_REGS_PARM3(ctx);
  const unsigned long long raw_arg3 = PT_REGS_PARM4(ctx);
  const unsigned long long raw_arg4 = PT_REGS_PARM5(ctx);

  reset_captured_args(fn);
  fn->arg_count = config->arg_count;
#pragma unroll
  for (int index = 0; index < DATACRUMBS_MAX_CAPTURE_ARGS; ++index) {
    if ((unsigned int)index >= config->arg_count) break;
    arg_index = config->arg_index[index];
    raw_value = 0;
    if (arg_index == 0) {
      raw_value = raw_arg0;
    } else if (arg_index == 1) {
      raw_value = raw_arg1;
    } else if (arg_index == 2) {
      raw_value = raw_arg2;
    } else if (arg_index == 3) {
      raw_value = raw_arg3;
    } else if (arg_index == 4) {
      raw_value = raw_arg4;
    }
    fn->args[index] = raw_value;
    fn->arg_data_status[index] = 0;
    fn->arg_data_len[index] = 0;
    __builtin_memset(fn->arg_data[index], 0, sizeof(fn->arg_data[index]));
    num_bytes = config->arg_num_bytes[index];
    if (num_bytes == 0) continue;
    if (num_bytes > DATACRUMBS_MAX_CAPTURE_BYTES) {
      num_bytes = DATACRUMBS_MAX_CAPTURE_BYTES;
    }
    if (config->arg_is_pointer[index] && raw_value != 0) {
      fn->arg_data_len[index] = num_bytes;
      if (config->probe_kind == DATACRUMBS_RUNTIME_PROBE_KIND_UPROBE) {
        err = bpf_probe_read_user(fn->arg_data[index], num_bytes, (const void*)raw_value);
      } else {
        err = bpf_probe_read_kernel(fn->arg_data[index], num_bytes, (const void*)raw_value);
      }
      fn->arg_data_status[index] = err == 0 ? 2 : 3;
      continue;
    }
    if (num_bytes > sizeof(raw_value)) {
      num_bytes = sizeof(raw_value);
    }
    fn->arg_data_len[index] = num_bytes;
    __builtin_memcpy(fn->arg_data[index], &raw_value, sizeof(raw_value));
    fn->arg_data_status[index] = 1;
  }
}

static inline __attribute__((always_inline)) void capture_runtime_raw_args(
    const struct runtime_event_config_t* config, struct fn_value_t* fn, unsigned long long raw_arg0,
    unsigned long long raw_arg1, unsigned long long raw_arg2, unsigned long long raw_arg3,
    unsigned long long raw_arg4, bool read_user_pointers) {
  unsigned int arg_index;
  unsigned int num_bytes;
  unsigned long long raw_value;
  long err;

  reset_captured_args(fn);
  fn->arg_count = config->arg_count;
#pragma unroll
  for (int index = 0; index < DATACRUMBS_MAX_CAPTURE_ARGS; ++index) {
    if ((unsigned int)index >= config->arg_count) break;
    arg_index = config->arg_index[index];
    raw_value = 0;
    if (arg_index == 0) {
      raw_value = raw_arg0;
    } else if (arg_index == 1) {
      raw_value = raw_arg1;
    } else if (arg_index == 2) {
      raw_value = raw_arg2;
    } else if (arg_index == 3) {
      raw_value = raw_arg3;
    } else if (arg_index == 4) {
      raw_value = raw_arg4;
    }
    fn->args[index] = raw_value;
    fn->arg_data_status[index] = 0;
    fn->arg_data_len[index] = 0;
    __builtin_memset(fn->arg_data[index], 0, sizeof(fn->arg_data[index]));
    num_bytes = config->arg_num_bytes[index];
    if (num_bytes == 0) continue;
    if (num_bytes > DATACRUMBS_MAX_CAPTURE_BYTES) {
      num_bytes = DATACRUMBS_MAX_CAPTURE_BYTES;
    }
    if (config->arg_is_pointer[index] && raw_value != 0) {
      fn->arg_data_len[index] = num_bytes;
      if (read_user_pointers) {
        err = bpf_probe_read_user(fn->arg_data[index], num_bytes, (const void*)raw_value);
      } else {
        err = bpf_probe_read_kernel(fn->arg_data[index], num_bytes, (const void*)raw_value);
      }
      fn->arg_data_status[index] = err == 0 ? 2 : 3;
      continue;
    }
    if (num_bytes > sizeof(raw_value)) {
      num_bytes = sizeof(raw_value);
    }
    fn->arg_data_len[index] = num_bytes;
    __builtin_memcpy(fn->arg_data[index], &raw_value, sizeof(raw_value));
    fn->arg_data_status[index] = 1;
  }
}

static inline __attribute__((always_inline)) void capture_runtime_usdt_args(
    struct pt_regs* ctx, const struct runtime_event_config_t* config, struct fn_value_t* fn) {
  long raw_value = 0;
  unsigned int num_bytes;
  long err;
  reset_captured_args(fn);
  fn->arg_count = config->arg_count;
#pragma unroll
  for (int index = 0; index < DATACRUMBS_MAX_CAPTURE_ARGS; ++index) {
    if ((unsigned int)index >= config->arg_count) break;
    raw_value = 0;
    if (bpf_usdt_arg(ctx, config->arg_index[index], &raw_value) != 0) {
      raw_value = 0;
    }
    fn->args[index] = (unsigned long long)raw_value;
    fn->arg_data_status[index] = 0;
    fn->arg_data_len[index] = 0;
    __builtin_memset(fn->arg_data[index], 0, sizeof(fn->arg_data[index]));
    num_bytes = config->arg_num_bytes[index];
    if (num_bytes == 0) continue;
    if (num_bytes > DATACRUMBS_MAX_CAPTURE_BYTES) {
      num_bytes = DATACRUMBS_MAX_CAPTURE_BYTES;
    }
    if (config->arg_is_pointer[index] && raw_value != 0) {
      fn->arg_data_len[index] = num_bytes;
      err = bpf_probe_read_user(fn->arg_data[index], num_bytes, (const void*)raw_value);
      fn->arg_data_status[index] = err == 0 ? 2 : 3;
      continue;
    }
    if (num_bytes > sizeof(raw_value)) {
      num_bytes = sizeof(raw_value);
    }
    fn->arg_data_len[index] = num_bytes;
    __builtin_memcpy(fn->arg_data[index], &raw_value, sizeof(raw_value));
    fn->arg_data_status[index] = 1;
  }
}

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx,
                                                               u64 attach_cookie) {
  // pid gate first: kprobes fire system-wide, so most hits are untraced processes. Bail before the
  // per-event config lookup to drop a map lookup on that path.
  struct fn_key_t key = {};
  u64 start_ts = 0;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = get_scratch_fn_value();
  if (fn == NULL) return 0;
  __builtin_memset(fn, 0, sizeof(*fn));
  fn->ts = bpf_ktime_get_ns();
  capture_runtime_args(ctx, config, fn);
  pmu_snapshot_entry(fn);
  bpf_map_update_elem(&fn_pid_map, &key, fn, BPF_ANY);
  DBG_PRINTK("Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx,
                                                               u64 attach_cookie) {
  // pid gate first (see generic_entry above): bail before the config lookup.
  struct fn_key_t key = {};
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = get_scratch_fn_value();
  if (fn == NULL) return 0;
  __builtin_memset(fn, 0, sizeof(*fn));
  fn->ts = bpf_ktime_get_ns();
  reset_captured_args(fn);
  bpf_map_update_elem(&fn_pid_map, &key, fn, BPF_ANY);
  DBG_PRINTK("Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
#endif
#else
static inline __attribute__((always_inline)) int generic_entry(struct pt_regs* ctx,
                                                               u64 attach_cookie) {
  return 0;
}
#endif
#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx,
                                                              u64 attach_cookie) {
  // pid gate first (see generic_entry): bail before the config + state lookups.
  struct fn_key_t key = {};
  u64 start_ts = 0;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  u64 te = bpf_ktime_get_ns();
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  DATACRUMBS_SKIP_SMALL_EVENTS(fn, te);
  if (hot_probe_drop(event_id, te)) return 0;  // rate-limit a runaway (busy-poll) probe
  struct generic_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct generic_event_t, event);
  event->type = config->probe_kind;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);
  copy_captured_args_to_event(fn, event);
  pmu_delta_exit(fn, event);
  DATACRUMBS_EVENT_SUBMIT(event, key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx,
                                                              u64 attach_cookie) {
  // pid gate first (see generic_entry): bail before the config + state lookups.
  struct fn_key_t key = {};
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  u64 te = bpf_ktime_get_ns();
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  struct profile_key_t profile_key = {};
  profile_key.type = 1;
  profile_key.id = key.id;
  profile_key.event_id = key.event_id;
  profile_key.time_interval = fn->ts / DATACRUMBS_TIME_INTERVAL_NS;
  struct profile_value_t* profile_value = bpf_map_lookup_elem(&profile, &profile_key);
  if (profile_value == NULL) {
    // Key not found, initialize a new value
    struct profile_value_t new_value;
    new_value.frequency = 0;
    new_value.duration = 0;
    bpf_map_update_elem(&profile, &profile_key, &new_value, BPF_NOEXIST);
    profile_value =
        bpf_map_lookup_elem(&profile, &profile_key);  // Lookup again to get the new value's address
  }
  if (profile_value != NULL) {
    profile_value->frequency++;
    profile_value->duration += (te - fn->ts);
    DBG_PRINTK("Captured event: %d, %d, %d, %d\n", profile_key.type, profile_key.id,
               profile_key.event_id, profile_key.time_interval);
  }
  bpf_map_update_elem(&latest_interval, &DATACRUMBS_TS_KEY, &profile_key.time_interval, BPF_ANY);
  return 0;
}
#endif
#else
static inline __attribute__((always_inline)) int generic_exit(struct pt_regs* ctx,
                                                              u64 attach_cookie) {
  return 0;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
static inline __attribute__((always_inline)) int generic_syscall_entry(
    struct pt_regs* ctx, u64 attach_cookie, unsigned long long arg0, unsigned long long arg1,
    unsigned long long arg2, unsigned long long arg3, unsigned long long arg4) {
  // pid gate first (see generic_entry): bail before the config lookup.
  struct fn_key_t key = {};
  u64 start_ts = 0;
  if (!need_tracing(&key, &start_ts)) {
    return 0;
  }
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = get_scratch_fn_value();
  if (fn == NULL) return 0;
  __builtin_memset(fn, 0, sizeof(*fn));
  fn->ts = bpf_ktime_get_ns();
  capture_runtime_raw_args(config, fn, arg0, arg1, arg2, arg3, arg4, true);
  pmu_snapshot_entry(fn);
  bpf_map_update_elem(&fn_pid_map, &key, fn, BPF_ANY);
  DBG_PRINTK("Pushed syscall pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_syscall_entry(
    struct pt_regs* ctx, u64 attach_cookie, unsigned long long arg0, unsigned long long arg1,
    unsigned long long arg2, unsigned long long arg3, unsigned long long arg4) {
  return 0;
}
#endif
#else
static inline __attribute__((always_inline)) int generic_syscall_entry(
    struct pt_regs* ctx, u64 attach_cookie, unsigned long long arg0, unsigned long long arg1,
    unsigned long long arg2, unsigned long long arg3, unsigned long long arg4) {
  return 0;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
static inline __attribute__((always_inline)) int usdt_entry(struct pt_regs* ctx,
                                                            u64 attach_cookie) {
  // pid gate first (see generic_entry): bail before the config lookup.
  struct fn_key_t key = {};
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = get_scratch_fn_value();
  if (fn == NULL) return 0;
  __builtin_memset(fn, 0, sizeof(*fn));
  fn->ts = bpf_ktime_get_ns();
  capture_runtime_usdt_args(ctx, config, fn);
  pmu_snapshot_entry(fn);
  bpf_map_update_elem(&fn_pid_map, &key, fn, BPF_ANY);
  DBG_PRINTK("USDT  Pushed pid:%d, event_id:%llu to map\n", (u32)key.id, event_id);
  return 0;
}

#else
static inline __attribute__((always_inline)) int usdt_entry(struct pt_regs* ctx,
                                                            u64 attach_cookie) {
  return 0;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
#if defined(DATACRUMBS_MODE) && (DATACRUMBS_MODE == 1)
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 attach_cookie,
                                                           long clazz, long method) {
  // pid gate first (see generic_entry): bail before the config + state lookups.
  struct fn_key_t key = {};
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  u64 te = bpf_ktime_get_ns();
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  DATACRUMBS_SKIP_SMALL_EVENTS(fn, te);
  if (hot_probe_drop(event_id, te)) return 0;  // rate-limit a runaway (busy-poll) probe
  struct generic_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct generic_event_t, event);
  event->type = config->probe_kind;
  event->id = key.id;
  event->event_id = event_id;
  DATACRUMBS_COLLECT_TIME(event);
  copy_captured_args_to_event(fn, event);
  pmu_delta_exit(fn, event);
  DATACRUMBS_EVENT_SUBMIT(event, key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 attach_cookie,
                                                           long clazz, long method) {
  // pid gate first (see generic_entry): bail before the config + state lookups.
  struct fn_key_t key = {};
  u64 start_ts;
  if (!need_tracing(&key, &start_ts)) {
    return 0;  // not tracing this pid
  }
  u64 te = bpf_ktime_get_ns();
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  key.event_id = event_id;
  struct fn_value_t* fn = bpf_map_lookup_elem(&fn_pid_map, &key);
  if (fn == 0) return 0;  // missed entry
  DATACRUMBS_SKIP_SMALL_EVENTS(fn, te);
  struct string_t local_str = {};                                                      // 100
  long len = bpf_probe_read_user_str(&local_str.str, MAX_STR_READ_LEN, (void*)clazz);  // 90
  local_str.len = len * 8;

#if defined(DATACRUMBS_ENABLE_INCLUSION_PATH) && (DATACRUMBS_ENABLE_INCLUSION_PATH == 1)
  int found = prefix_search(&inclusion_path_trie, &local_str);
  if (!found) {
    DBG_PRINTK("Skipping usdt for %s as it is not in inclusion path trie\n", local_str.str);
    return 0;  // Skip if not in inclusion path
  }
#endif
  struct usdt_profile_key_t profile_key = {};
  profile_key.type = 3;
  profile_key.id = key.id;
  profile_key.event_id = key.event_id;
  u32 class_hash = hash_and_store(&local_str, len);                                // 100
  len = bpf_probe_read_user_str(&local_str.str, MAX_STR_READ_LEN, (void*)method);  // 90
  u32 method_hash = hash_and_store(&local_str, len);
  profile_key.class_hash = class_hash;
  profile_key.method_hash = method_hash;
  profile_key.time_interval = fn->ts / DATACRUMBS_TIME_INTERVAL_NS;
  struct profile_value_t* profile_value = bpf_map_lookup_elem(&usdt_profile, &profile_key);
  if (profile_value == NULL) {
    // Key not found, initialize a new value
    struct profile_value_t new_value;
    bpf_map_update_elem(&usdt_profile, &profile_key, &new_value, BPF_NOEXIST);
    profile_value = bpf_map_lookup_elem(
        &usdt_profile, &profile_key);  // Lookup again to get the new value's address
  }
  if (profile_value != NULL) {
    profile_value->frequency++;
    profile_value->duration += (te - fn->ts);
    DBG_PRINTK("Captured usdt event: %d, %d, %d, %d\n", profile_key.type, profile_key.id,
               profile_key.event_id, profile_key.time_interval);
  }
  bpf_map_update_elem(&latest_interval, &DATACRUMBS_TS_KEY, &profile_key.time_interval, BPF_ANY);
  return 0;
}
#endif
#else
static inline __attribute__((always_inline)) int usdt_exit(struct pt_regs* ctx, u64 event_id,
                                                           long clazz, long method) {
  return 0;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1) && defined(DATACRUMBS_MODE) && \
    (DATACRUMBS_MODE == 1)
// Tracepoint handler: ctx is the raw tracepoint record. A tracepoint is a point event, so this emits
// directly (no entry/exit pairing). Fields are read from ctx at offsets parsed from the tracepoint's
// tracefs format at attach.
static inline __attribute__((always_inline)) int generic_point(void* ctx, u64 attach_cookie) {
  const u64 now = bpf_ktime_get_ns();
  const struct runtime_event_config_t* config = resolve_event_config(attach_cookie);
  if (config == NULL) return 0;
  const u64 event_id = config->event_id;
  struct fn_key_t key = {};
  if (config->system_wide) {
    key.id = bpf_get_current_pid_tgid();  // capture on all pids
  } else {
    u64 start_ts = 0;
    if (!need_tracing(&key, &start_ts)) return 0;  // default: pid-gated like kprobes
  }
  if (hot_probe_drop(event_id, now)) return 0;  // rate-limit a runaway (esp. system-wide) tracepoint
  struct generic_event_t* event;
  DATACRUMBS_RB_RESERVE(output, struct generic_event_t, event);
  event->type = config->probe_kind;
  event->id = key.id;
  event->event_id = event_id;
  event->ts = now;
  event->dur = 1;  // nominal: a tracepoint is instantaneous; writer emits 1us so the ph:"X" renders
  event->arg_count = config->arg_count;
#pragma unroll
  for (int i = 0; i < DATACRUMBS_MAX_CAPTURE_ARGS; ++i) {
    if ((unsigned int)i >= config->arg_count) break;
    event->args[i] = 0;
    event->arg_data_len[i] = 0;
    event->arg_data_status[i] = 0;
    unsigned int nb = config->arg_num_bytes[i];
    if (nb == 0) continue;
    const void* src = (const char*)ctx + config->arg_offset[i];
    if (config->arg_is_pointer[i]) {
      if (config->arg_index[i] == 1) {  // __data_loc dynamic string: field holds [len:16|rel_off:16]
        unsigned int loc = 0;
        bpf_probe_read_kernel(&loc, 4, src);
        unsigned int dl_len = (loc >> 16) & 0xffff;
        unsigned int dl_off = loc & 0xffff;
        if (dl_len > DATACRUMBS_MAX_CAPTURE_BYTES) dl_len = DATACRUMBS_MAX_CAPTURE_BYTES;
        if (dl_len > 0 &&
            bpf_probe_read_kernel(event->arg_data[i], dl_len, (const char*)ctx + dl_off) == 0) {
          event->arg_data_len[i] = dl_len;
          event->arg_data_status[i] = 2;
        }
      } else {  // fixed char array (e.g. comm[16]) -> raw bytes
        if (nb > DATACRUMBS_MAX_CAPTURE_BYTES) nb = DATACRUMBS_MAX_CAPTURE_BYTES;
        if (bpf_probe_read_kernel(event->arg_data[i], nb, src) == 0) {
          event->arg_data_len[i] = nb;
          event->arg_data_status[i] = 2;
        }
      }
    } else {  // scalar field
      unsigned long long v = 0;
      if (nb > 8) nb = 8;
      bpf_probe_read_kernel(&v, nb, src);
      event->args[i] = v;
    }
  }
  DATACRUMBS_EVENT_SUBMIT(event, key.id, event_id);
  return 0;
}
#else
static inline __attribute__((always_inline)) int generic_point(void* ctx, u64 attach_cookie) {
  return 0;
}
#endif

#if defined(DATACRUMBS_ENABLE) && (DATACRUMBS_ENABLE == 1)
static inline __attribute__((always_inline)) int generic_fork_exit(struct pt_regs* ctx,
                                                                   u64 event_id) {
  struct fn_key_t key = {};
  key.event_id = event_id;
  u64 start_ts;
  if (need_tracing(&key, &start_ts)) {
    u64 tsp = bpf_ktime_get_ns();
    u32 pid = PT_REGS_RC(ctx);
    (void)pid;
    if (pid != 0) {
      DBG_PRINTK("Collect forked tracing PID %d", pid);
      bpf_map_update_elem(&pid_map, &pid, &tsp, BPF_ANY);
    }
  }
  return generic_exit(ctx, event_id);
}

#else
static inline __attribute__((always_inline)) int generic_fork_exit(struct pt_regs* ctx,
                                                                   u64 event_id) {
  return 0;
}
#endif

char LICENSE[] SEC("license") = "Dual BSD/GPL";
#endif  // __DATACRUMBS_SERVER_BPF_COMMON_H
