#ifndef __DATACRUMBS_COMMON_CONSTANTS_H
#define __DATACRUMBS_COMMON_CONSTANTS_H
#define DATACRUMBS_PROBE_CATEGORY "DC"
#define START_FUNCTION_NAME "start"
#define START_EVENT_ID 1
#define END_FUNCTION_NAME "end"
#define END_EVENT_ID 2
#ifndef DATACRUMBS_MAX_PMU
#define DATACRUMBS_MAX_PMU 3  // max hardware counters read per event (entry/exit delta)
#endif

#define DATACRUMBS_ENV_AUTODETACH "DATACRUMBS_AUTODETACH"
#define DATACRUMBS_ENV_BPFTIME_HOT "DATACRUMBS_BPFTIME_HOT"
#define DATACRUMBS_ENV_BPFTIME_SHM_NAME "DATACRUMBS_BPFTIME_SHM_NAME"
#define DATACRUMBS_ENV_BPFTIME_SHM_MEMORY_MB "DATACRUMBS_BPFTIME_SHM_MEMORY_MB"
#define DATACRUMBS_ENV_BPFTIME_VM_NAME "DATACRUMBS_BPFTIME_VM_NAME"
#define DATACRUMBS_ENV_HEARTBEAT_S "DATACRUMBS_HEARTBEAT_S"
#define DATACRUMBS_ENV_LOG_DIR_NAME "DATACRUMBS_LOG_DIR"
#define DATACRUMBS_ENV_MAX_QUEUE_EVENTS "DATACRUMBS_MAX_QUEUE_EVENTS"
#define DATACRUMBS_ENV_NIC_DEVICES "DATACRUMBS_NIC_DEVICES"
#define DATACRUMBS_ENV_NIC_NETDEVS "DATACRUMBS_NIC_NETDEVS"
#define DATACRUMBS_ENV_PLUGINS "DATACRUMBS_PLUGINS"
#define DATACRUMBS_ENV_SERVICE_RUN_ID "DATACRUMBS_SERVICE_RUN_ID"
#define DATACRUMBS_ENV_STALL_BUDGET_MS "DATACRUMBS_STALL_BUDGET_MS"
#define DATACRUMBS_ENV_TASK_COUNTERS "DATACRUMBS_TASK_COUNTERS"
#define DATACRUMBS_ENV_TELEMETRY_INTERVAL_MS "DATACRUMBS_TELEMETRY_INTERVAL_MS"
#define DATACRUMBS_ENV_UNCORE_EVENTS "DATACRUMBS_UNCORE_EVENTS"
#define DATACRUMBS_ENV_WRITER_THREADS "DATACRUMBS_WRITER_THREADS"
#define DATACRUMBS_ENV_ZLIB_LEVEL "DATACRUMBS_ZLIB_LEVEL"
#define DATACRUMBS_BPFTIME_ENV_SHM_NAME "BPFTIME_SHM_NAME"
#define DATACRUMBS_BPFTIME_ENV_SHM_MEMORY_MB "BPFTIME_SHM_MEMORY_MB"
#define DATACRUMBS_BPFTIME_ENV_VM_NAME "BPFTIME_VM_NAME"

// Sized here, not beside either struct: the BPF and userspace views of one event must agree.
#define DATACRUMBS_MAX_CAPTURE_ARGS 5
#define DATACRUMBS_MAX_CAPTURE_BYTES 64
#define DATACRUMBS_STACK_DEPTH 32
#define DATACRUMBS_STACKDUMP_BYTES 4000
#define DATACRUMBS_STACK_SAMPLE_TYPE 200u  // generic_event_t.type sentinel for a stack sample
#define MAX_STR_READ_LEN 256

#endif  // __DATACRUMBS_COMMON_CONSTANTS_H
