include("${CMAKE_CURRENT_LIST_DIR}/datacrumbs_utils_compatibility.cmake")

if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "OUTPUT must point to the env file to write")
endif()

if(NOT DEFINED DATACRUMBS_UTILS_COMPATIBLE_REPOSITORY OR DATACRUMBS_UTILS_COMPATIBLE_REPOSITORY
                                                         STREQUAL ""
)
  message(FATAL_ERROR "DATACRUMBS_UTILS_COMPATIBLE_REPOSITORY is not defined")
endif()

if(NOT DEFINED DATACRUMBS_UTILS_COMPATIBLE_REF OR DATACRUMBS_UTILS_COMPATIBLE_REF STREQUAL "")
  message(FATAL_ERROR "DATACRUMBS_UTILS_COMPATIBLE_REF is not defined")
endif()

file(
  WRITE "${OUTPUT}"
  "DATACRUMBS_UTILS_COMPATIBLE_REPOSITORY=${DATACRUMBS_UTILS_COMPATIBLE_REPOSITORY}\nDATACRUMBS_UTILS_COMPATIBLE_REF=${DATACRUMBS_UTILS_COMPATIBLE_REF}\n"
)
